using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace petDashboard
{
    public partial class FormProjetos : Form
    {
        public FormProjetos(string projeto)
        {
            InitializeComponent();
            this.Name = projeto;

            if (projeto == "hospital")
            {
                ProjetoHospital();
            } 
            else if (projeto == "aula")
            {
                ProjetoAulas();
            }
            else if (projeto == "cinepet")
            {
                ProjetoCine();
            }
            else if (projeto == "laboratio")
            {
                ProjetoLab();
            }
            else if (projeto == "evento")
            {
                ProjetoEventos();
            }
            else if (projeto == "aula")
            {
                ProjetoAulas();
            }
            else if (projeto == "seminario")
            {
                ProjetoSeminarios();
            }
        }

        public void ProjetoHospital()
        {
            projeto.Text = "Hospital de Custodia";
            conteudo.Text = Environment.NewLine + "Descrição/Justificativa:" + Environment.NewLine + Environment.NewLine + "O Hospital de Custódia (HC) foi criado pela Lei no. 4.559, de 07 de janeiro de 1971, é um órgão oficial depsiquiatria forense de Santa Catarina, integrante do Sistema Prisional do Estado, ligado ao Departamento deAdministração Prisional (DEAP) e subordinado à Secretaria de Estado de Justiça e Cidadania (SJC/SC). Tem comofinalidade custodiar e tratar pessoas do sexo masculino em medida de segurança, que tenham cometido delitoquando em transtorno mental e que, do ponto de vista psiquiátrico-forense, tenham sido consideradas inimputáveis,à época dos fatos, conforme os Arts. 96 e 97 do Código Penal Brasileiro. Atualmente, a instituição abriga cerca de50 pessoas com transtorno mental e em conflito com a lei. Mediante parecer do psiquiatra da instituição, alguns internos podem participar de atividades para sua reabilitação psicossocial. Tais atividades englobam um conjuntode estratégias destinadas a oferecer oportunidades de aquisição / troca de conhecimentos e experiências saudáveispara a reinserção do interno na sociedade. O processo terapêutico de reabilitação psicossocial deve permitir eestimular a inserção social e o desenvolvimento de potencialidades com o objetivo de resgatar a sua autonomia bemcomo a ampliação das trocas sociais, afetivas, materiais e simbólicas. O PET Computação, em parceria comprofessores do Departamento de Ciências da Informação (CIn) da UFSC, propõe o desenvolvimento de oficinas deinclusão digital aos internos do HC com vistas a colaborar no processo de reintegração daquelas pessoas nasociedade. Através de atividades semanais, pretende-se apresentar aos internos alguns recursos computacionais esoftwares para que eles, na medida das suas possibilidades, possam explorar tais elementos de maneira que estasexperiências se revertam em ganhos pessoais e emocionais. Alguns recursos computacionais que serãoapresentados são: aplicativos para editoração de textos, vídeos e imagens; jogos educativos (ensino de línguasestrangeiras, lógica, matemática, história, etc), programação de computadores e outros recursos conforme demandado grupo de internos que serão atendidos por esta oficina.";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Objetivos:" + Environment.NewLine + Environment.NewLine + "Os objetivos desta atividade podem ser divididos em dois grupos: 1. Objetivos definidos pelo Art. 2 da Portaria976, de 2010: Este artigo apresenta 8 objetivos que devem orientar todas as atividades dos grupos PET. Emespecífico, o seguinte objetivo será contemplado com a atividade que estamos propondo: V - estimular o espíritocrítico, bem como a atuação profissional pautada pela cidadania e pela função social da educação superior; Aparticipação do PET Computação nesta atividade realça seu papel social, sua cidadania e estimula o espírito críticodo grupo. 2. Objetivos do PET enquanto espaço de aproximação da universidade e sociedade: entendemos que oPET Computação pode apoiar o processo de reabilitação psicossocial das pessoas com transtorno mental emconflito com a lei. Neste sentido, esta atividade se revela com potencial para alicerçarmos ainda mais algumasparcerias da universidade com outras instituições sociais.";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Como a atividade será realizada? (Metodologia):" + Environment.NewLine + Environment.NewLine + "A atividade será organizada da seguinte forma: No retorno do grupo PET às suas atividades acadêmicas(normalmente início de fevereiro) define-se quais bolsistas poderão ministrar as oficinas e quais bolsistas irãoauxiliar na confecção dos materiais usados nas oficinas. As oficinas serão semanais, 1 vez por semana e cadaencontro com duração de 1 hora. Nas atividades semanais, iremos apresentar aos internos alguns recursoscomputacionais e softwares para que eles, na medida das suas possibilidades, possam explorar tais elementos demaneira que estas experiências se revertam em ganhos pessoais e emocionais. Alguns recursos computacionais queserão apresentados são: aplicativos para editoração de textos, vídeos e imagens; jogos educativos (ensino de línguasestrangeiras, lógica, matemática, história, etc), programação de computadores e outros recursos conforme demandado grupo de internos que serão atendidos por esta oficina.";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Resultados / produtos esperados com a atividade: melhorias para o Curso, para a Educação, para asociedade, meios para a socialização dos resultados, publicações, etc:" + Environment.NewLine + Environment.NewLine + "Esperam-se resultados positivos para os internos do HC e para o grupo PET Computação. Para os internos,esperamos que estas oficinas realmente colaborem com sua melhora e reinserção na sociedade. Para o PETComputação, espera-se a ampliação das competências dos bolsistas acerca da realização das oficinas. Outroresultado esperado se refere à elaboração de um relatório contendo o registro desta atividade, listas de presença,registro fotográfico e / ou em vídeo dos encontros, depoimentos dos internos e dos bolsistas PET participantes doprojeto, apontamentos sobre dificuldades / facilidades encontradas na realização da atividade. Tal relatório poderáservir de base para o aprimoramento da atividade ou mesmo a extensão dela, com vistas a participar de maneira mais efetiva do Programa de Alta Progressiva do HC, na qual os internos possam participar das oficinas em umlocal (ambiente físico) fora do HC.";
        }
        public void ProjetoAulas()
        {
            projeto.Text = "Aulas";
            conteudo.Text = Environment.NewLine + "Descrição/Justificativa:" + Environment.NewLine + Environment.NewLine + "Os cursos de graduação em Ciências da Computação (CCO) e Sistemas de Informação (SIN) são cursos densos, deformação ampla e profunda sobre as principais áreas da computação. A velocidade com que evoluem novosconceitos e paradigmas de desenvolvimento de sistemas computacionais faz com que atividades complementaressejam desenvolvidas junto aos graduandos como forma de apresentar e ensinar estas novas técnicas, paradigmas,linguagens de programação, frameworks, etc. Neste sentido, os bolsistas do PET propõem uma atividade para aformação complementar dos graduandos em Ciência da Computação e Sistemas de Informação, promovendo arealização de minicursos em assuntos atuais e de interesse da comunidade acadêmica. Essencialmente, busca-setrazer para o âmbito dos cursos de graduação assuntos que não foram ministrados em sala de aula e que, na opiniãodo grupo são necessários. Esta atividade é também aberta para a comunidade, sendo que a divulgação é realizadaprincipalmente pelas mídias sociais de maior impacto hoje (FaceBook e site do grupo PET Computação).";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Objetivos:" + Environment.NewLine + Environment.NewLine + "Levar o conhecimento de assuntos não abordados em sala, ou com foco diferenciado, para gerar interesse nasdiversas áreas da computação e sistemas de informação, além de capacitar os graduandos em assuntosdiferenciados. Por outro lado, reforçar o papel de transmissor de informação dos petianos. Em atendimento àPortaria n.976, esta atividade engloba os seguintes objetivos gerais do Programa de Educação Tutorial (incisos I aV do Art. 2º): I - desenvolver atividades acadêmicas em padrões de qualidade de excelência, mediante grupos deaprendizagem tutorial de natureza coletiva e interdisciplinar; II - contribuir para a elevação da qualidade daformação acadêmica dos alunos de graduação; III - estimular a formação de profissionais e docentes de elevadaqualificação técnica, científica, tecnológica e acadêmica; IV - formular novas estratégias de desenvolvimento emodernização do ensino superior no país; V - estimular o espírito crítico, bem como a atuação profissional pautadapela cidadania e pela função social da educação superior.";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Como a atividade será realizada? (Metodologia):" + Environment.NewLine + Environment.NewLine + "Esta atividade possui carga horária anual de 78 horas, sendo 2 horas por semana por 35 semanas letivas e maisquatro semanas não letivas (11/02 a 08/03). A atividade é organizada em três etapas: 1. Pesquisa e definição dotema (assunto) que será estudado e posteriormente ensinado aos graduandos. Esta pesquisa considera a opinião esolicitação dos próprios graduandos dos cursos assim como a opinião do grupo PET sobre o tema proposto. 2.Define-se a equipe que irá trabalhar nesta atividade, isto é, quais petianos irão confeccionar / organizar os materiaisdidáticos, quais bolsistas irão realizar a divulgação e aplicação da atividade para o grupo de graduandosinteressados no tema proposto. As equipes definem um cronograma considerando as tarefas anteriormentedescritas. São também discutidas formas inovadoras para a transmissão dos conteúdos, buscando formas maisatrativas, eficientes e que elevem o padrão de qualidade dos cursos de graduação envolvidos. 3. A atividade érealizada: preparação dos conteúdos e materiais que serão usados, reserva de sala de aula ou laboratório deinformática, aplicação do minicurso, posterior elaboração de relatórios e avaliação da atividade pelos bolsistas queexecutaram a atividade e pelo grupo de graduandos que se inscreveu no minicurso";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Resultados / produtos esperados com a atividade: melhorias para o Curso, para a Educação, para asociedade, meios para a socialização dos resultados, publicações, etc:" + Environment.NewLine + Environment.NewLine + "Ao final desta atividade, espera-se um conjunto de minicursos de autoria do grupo PET Computação sobre temasatuais da computação e de áreas afins. A confecção de materiais didáticos e relatórios também são resultadosalmejados. Na perspectiva dos bolsistas PET, espera-se que esta atividade promova a ampliação de seuconhecimento acadêmico sobre um determinado tema bem como o amadurecimento sobre a gerência de realizaçãode atividades deste tipo - minicursos. A integração do PET com os alunos de graduação é outro resultado esperado.Como é uma atividade aberta para a comunidade, entendemos que a participação de estudantes e profissionais quenão estão na universidade (isto é, não são alunos matriculados em cursos de graduação da UFSC) é um retorno queo PET proporciona para a sociedade. Conforme § 1º e § 2º do Art. 3 da Portaria 976: ¿(¿) § 1° O grupo PETdevera¿ realizar atividades que possibilitem uma formação acadêmica ampla aos estudantes e que envolvam ensino,pesquisa e extensão. § 2° Os grupos PET deverão contribuir para a implementação de políticas públicas e dedesenvolvimento em sua área de atuação, sendo que esta contribuição sera¿ considerada por ocasião das avaliaçõesperiódicas.¿ Acreditamos que esta atividade está em consonância com os resultados apreciados pelas diretrizesgerais do Programa de Educação Tutorial.";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Qual será a metodologia de avaliação da atividade pelo grupo:" + Environment.NewLine + Environment.NewLine + "Após a realização dos minicursos ocorrerá uma reunião com os bolsistas para avaliar a qualidade das aulas,ponderando os pontos fortes e os fracos da atividade, assim como formar ideias para o aperfeiçoamento dos mesmos. Será também disponibilizado um questionário online para que os participantes dos minicursos possaminformar sua opinião sobre o conteúdo ministrado, a forma como o minicurso foi conduzido, materiais didáticosutilizados, organização dos tópicos no período do minicurso e outras informações relevantes.";
        }

        public void ProjetoCine()
        {
            projeto.Text = "Cinepet";
            conteudo.Text = Environment.NewLine + "Descrição/Justificativa:" + Environment.NewLine + Environment.NewLine + "A língua inglesa é indispensável para profissionais e estudantes de computação e áreas afins, sendo extensivamenteusada em novas publicações da área, documentação de softwares e também na internet. Como forma de incentivo aprática do inglês, adotaremos métodos semanais para a melhora do idioma.";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Objetivos:" + Environment.NewLine + Environment.NewLine + "O principal objetivo é a melhoria da proficiência da língua inglesa. Espera-se, com esta atividade, que ashabilidades de comunicação oral e escrita sejam aprimoradas. Utilizar a lingua inglesa semanalmente para discutirtarefas do dia-a-dia dos bolsistas e outros assuntos que estejam em pauta no momento fará uma diferençasignificativa ao final de um ano de atividade. A atividade proporciona o fortalecimento da segurança do bolsista aocomunicar-se com os demais colegas e outros estudantes estrangeiros que estejam no departamento.";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Como a atividade será realizada? (Metodologia):" + Environment.NewLine + Environment.NewLine + "Serão definidos horários durante a semana em que todos do grupo devem comunicar-se exclusivamente em inglês,não somente por fala mas em e-mails internos e quaisquer outros meios de comunicação. Como a maioria do grupopossui noções básicas de inglês, O PET Computação tem incentivado o aprendizado de uma segunda línguaestrangeira, como forma de complementar para a formação dos bolsistas.";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Resultados / produtos esperados com a atividade: melhorias para o Curso, para a Educação, para asociedade, meios para a socialização dos resultados, publicações, etc:" + Environment.NewLine + Environment.NewLine + "primeiro resultado é o aprimoramento do bolsista enquanto estudante de graduação e sua preparação para a vidaprofissional. A melhoria para o curso é, sem dúvida, o resultado mais apreciado. Na medida em que os alunosbuscam aprimoramento em uma segunda língua, o interesse por assuntos relacionados (ou que dependem doidioma) se amplia. Com isso, o curso ganha alunos mais interessados e dedicados a sua formação.";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Qual será a metodologia de avaliação da atividade pelo grupo:" + Environment.NewLine + Environment.NewLine + "Ao final de cada semestre, será aplicado uma prova prática buscando medir a qualidade de interpretação dosalunos. Além disso, cada bolsista fará uma auto-avaliação tendo em conta o domínio oral e escrito do idioma.";
        }
        public void ProjetoLab()
        {
            projeto.Text = "Laboratorios";
            conteudo.Text = Environment.NewLine + "Descrição/Justificativa:" + Environment.NewLine + Environment.NewLine + "Algumas disciplinas dos cursos de Ciências da Computação e Sistemas de Informação exigem grande empenho ededicação dos alunos. Muitas vezes, estudantes das fases iniciais destes cursos precisam de apoio extra-classe(atendimentos individualizados com o professor e / ou monitor da disciplina, engajamento em grupos de estudos).Neste contexto, o PET Computação se disponibiliza a atender estudantes com dúvidas ou dificuldades em certasdisciplinas. Esta atividade vem sendo realizada a alguns anos e percebemos sua importância na medida em o PETtorna-se referência como ponto de apoio aos estudantes cursando estas disciplinas.";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Objetivos:" + Environment.NewLine + Environment.NewLine + "Esta atividade está em consonância com os principais objetivos do Programa de Educação Tutorial, conformePortaria n.976, a saber: - Desenvolver atividades acadêmicas em padrões de qualidade de excelência, mediantegrupos de aprendizagem tutorial de natureza coletiva e interdisciplinar; - Contribuir para a elevação da qualidadeda formação acadêmica dos alunos de graduação; - Introduzir novas práticas pedagógicas na graduação. De um lado, existe o objetivo de que o petiano aprenda e colabore com o professor em sala de aula, aproximando os alunosdos conteúdos estudados. De outro lado, existe o objetivo de que o petiano seja um agente transformador nasdisciplinas da graduação, levando os conteúdos de uma forma mais interessante para seus colegas.";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Como a atividade será realizada? (Metodologia):" + Environment.NewLine + Environment.NewLine + "Alguns professores do departamento ou estudantes que estão sentindo dificuldade em alguma disciplina solicitamapoio ao PET. Este se organiza em torno da atividade proposta pelo professor, as quais podem ser: resolução delistas de exercícios ou atividades práticas em sala de aula. Então os bolsistas desenvolvem alguma estratégia paraestimular os alunos a participarem da atividade proposta e sob a supervisão do professor da disciplina, a atividade érealizada. Além disso, os alunos poderão marcar horários em que podem tirar dúvidas com os petianos, que estãomais próximos deles e tem maior disponibilidade de horários para atendimento.";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Resultados / produtos esperados com a atividade: melhorias para o Curso, para a Educação, para asociedade, meios para a socialização dos resultados, publicações, etc:" + Environment.NewLine + Environment.NewLine + "Alguns professores do departamento ou estudantes que estão sentindo dificuldade em alguma disciplina solicitamapoio ao PET. Este se organiza em torno da atividade proposta pelo professor, as quais podem ser: resolução delistas de exercícios ou atividades práticas em sala de aula. Então os bolsistas desenvolvem alguma estratégia paraestimular os alunos a participarem da atividade proposta e sob a supervisão do professor da disciplina, a atividade érealizada. Além disso, os alunos poderão marcar horários em que podem tirar dúvidas com os petianos, que estãomais próximos deles e tem maior disponibilidade de horários para atendimento.";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Qual será a metodologia de avaliação da atividade pelo grupo:" + Environment.NewLine + Environment.NewLine + "São esperados resultados em três esferas acadêmicas: aprimoramento do bolsista no entendimento do conteúdo emque ele auxiliou os demais colegas, ganho de desempenho por parte do aluno (ou alunos) que buscaram este apoiojunto ao PET e melhora na disciplina, na medida em que aqueles alunos que buscaram apoio e foram atendidosalcançam melhor desempenho na turma e atuam como agentes divulgadores das atividades do PET junto agraduação.";
        }
        public void ProjetoEventos()
        {
            projeto.Text = "Eventos";
            conteudo.Text = Environment.NewLine + "Descrição/Justificativa:" + Environment.NewLine + Environment.NewLine + "Participação dos alunos do PET em eventos relacionados ao programa, como: EnaPET (Encontro Nacional dosGrupos PET), SulPET (Encontro Regional dos Grupos PETs da Região Sul do Brasil), InterPET-SC e também emeventos na área de computação: FISL (Fórum Internacional Software Livre), CSBC (Congresso da SociedadeBrasileira de Computação) e semanas acadêmicas de outros grupos PET Computação.";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Objetivos:" + Environment.NewLine + Environment.NewLine + "Propiciar aos bolsistas PET a ampliação das relações acadêmicas com membros de diferentes PETs, com outrospesquisadores de diversas áreas de pesquisa e outros acadêmicos de diferentes Universidades (nível de graduação,mestrado e doutorado).";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Como a atividade será realizada? (Metodologia):" + Environment.NewLine + Environment.NewLine + "Os eventos acadêmicos de interesse dos bolsistas serão definidos em reuniões do grupo. Será definido quaisbolsistas irão participar. Esta atividade depende da disponibilização do valor referente a verba de custeio paraauxiliar no pagamento das despesas da(s) viagem(ns). No retorno, os alunos apresentam relatórios sobre aparticipação no evento e descrevem o quão significativa foi a experência na sua formação acadêmica. Estaatividade proporciona a abertura de dialógos sobre como melhorar as práticas usadas no grupo tanto no que se refere ao planejamento das atividades quando nas suas execuções. A atividade prevê 78 horas, sendo 40 horasdestinadas à participação do Enapet (1 semana, 40 horas), Sulpet ( 3 dias, 24 horas) e Interpet (1 por semestre comaproximadamente 7 horas em cada evento).";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Resultados / produtos esperados com a atividade: melhorias para o Curso, para a Educação, para asociedade, meios para a socialização dos resultados, publicações, etc:" + Environment.NewLine + Environment.NewLine + "O principal resultado esperado é o fortalecimento do Grupo de Educação Tutorial através da troca de experiênciasentre os membros de diferentes grupos no país. Um segundo resultado esperado se refere a formação complementardo estudante na medida em que a participação em eventos de natureza acadêmica ampliam seu referencialacadêmico.";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Qual será a metodologia de avaliação da atividade pelo grupo:" + Environment.NewLine + Environment.NewLine + "Após a participação no evento, o bolsista apresentará um relatório descrevendo as atividades realizadas e aexperiência adquirida. Além disso, verifica-se o interesse do grupo em participar deste evento no próximo ano. Estaanálise deve levar em conta o ganho acadêmico do estudante em relação a esta participação.";
        }
        public void ProjetoSeminarios()
        {
            projeto.Text = "Seminarios";
            conteudo.Text = Environment.NewLine + "Descrição/Justificativa:" + Environment.NewLine + Environment.NewLine + "Ensino, pesquisa e extensão compõem as bases das universidades brasileiras. A pesquisa científica tem um fortepapel no desenvolvimento da própria universidade bem como no desenvolvimento econômico, tecnológico,ambiental e social do país. Neste sentido, o Programa de Educação Tutorial deve realizar atividades que incentivemos estudantes a investir no aprimoramento da sua capacidade de realizar pesquisas no âmbito de seusdepartamentos e cursos de graduação. A pesquisa científica incorpora várias etapas de desenvolvimento, como ainvestigação, a proposição de novas teorias e soluções, testes e análise. Esta atividade propõe a realização de umadas etapas da pesquisa científica, que é o estudo e a apresentação de artigos científicos em áreas da computação quesão de interesse dos bolsistas deste PET. Por ser uma área ampla, multidisciplinar e que permeia todas as demaisáreas, o correto encaminhamento de pesquisa torna-se fundamental para que o bolsista possa obter êxito nestaatividade.";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Objetivos:" + Environment.NewLine + Environment.NewLine + "Possibilitar aos bolsistas um estudo dirigido sobre tema de uma área de pesquisa da Computação, aprimorando acapacidade de crítica e entendimento das propostas discutidas sobre o estado da arte do tema em questão, além dedesenvolver a oratória dos membros.";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Como a atividade será realizada? (Metodologia):" + Environment.NewLine + Environment.NewLine + "Esta atividade possui carga horária de 78 horas, sendo 2 horas por semana por 35 semanas letivas e mais quatrosemanas não letivas (11/02 a 08/03). A forma de trabalho desta atividade se divide em quatro etapas: 1. Busca deartigos nas principais bases de dados científicas (IEEE Xplorer, ACM, Science Direct e outras) com a definição depalavras-chaves sobre o tema de interesse. Em cada base científica, informa-se que o período para a busca se refereaos últimos cinco anos. Ao final desta etapa tem-se um conjunto bastante significativo de artigos relacionados. 2.Dos artigos encontrados na etapa anterior, faz-se uma seleção com base na leitura dos titulos e abstracts dos artigos.Espera-se uma redução expressiva no número de artigos de interesse. Ao final desta etapa, o aluno elabora umatabela com 10-15 artigos onde consta: título, autores, universidade do artigo, ano de publicação, principaiscaracterísticas da proposta. 3. De posse da tabela definida na etapa anterior, verifica-se o Qualis CC (Ciência daComputação) dos eventos e periódicos que constam na tabela. Escolhe-se 5-6 artigos que possuem Qualis CC noextrato superior (A1, A2 e B1). 4. Em reunião com a tutora do grupo, realiza-se a análise dos artigos selecionadosna etapa anterior para determinação de qual artigo será apresentado ao grupo. O critério de escolha do artigo levaem consideração os seguintes aspectos: dificuldade técnica em entender a proposta e aderência da proposta ao temade interesse do aluno. Outros aspectos podem ser levados em consideração e são tratados caso a caso.";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Resultados / produtos esperados com a atividade: melhorias para o Curso, para a Educação, para asociedade, meios para a socialização dos resultados, publicações, etc:" + Environment.NewLine + Environment.NewLine + "Um primeiro resultado que se espera é o desenvolvimento de algumas habilidades de pesquisa científica dobolsista. Espera-se que ao final desta atividade, o aluno seja capaz de fazer buscas corretas considerando um temade pesquisa, que saiba selecionar corretamente os artigos mais relevantes para o estudo e que consiga interpretarcorretamente a proposta bem como escrever e apresentar sobre ela. Obviamente, uma pesquisa científica englobaoutras atividades como investigação, análise e testes de propostas. A atividade proposta neste planejamentoconsidera o primeiro passo da pesquisa científica, que se refere a leitura e estudo de propostas já existentes sendoela a base para as atividades seguintes do processo de pesquisa científica. Um segundo resultado diz respeito ainserção do bolsista em uma tema de pesquisa que poderá ser desdobrado em participação em projetos de pesquisascom professores que atuam na área em questão e também nos primeiros passos em direção ao início do trabalho deconclusão de curso (TCC) do bolsista. Este segundo resultado se reflete em um retorno para a sociedade na medidaem que entregamos profissionais bem qualificados e preparados para atuarem em centros de pesquisa euniversidades, alavancando o desenvolvimento científico e sócio-econômico.";
            conteudo.Text += Environment.NewLine + Environment.NewLine + Environment.NewLine + "Qual será a metodologia de avaliação da atividade pelo grupo:" + Environment.NewLine + Environment.NewLine + "Para cada artigo apresentado, a avaliação se dará em duas etapas: 1. Entrega da resenha: avalia-se a capacidade deescrita do bolsista, propondo correções e melhorias no texto: correções ortográficas, estruturação do texto,sequenciação dos conteúdos relacionados. 2. Apresentação do artigo: avalia-se a clareza nas explicações, gerênciacorreta do tempo proposto para a apresentação, qualidade do material visual usado nas apresentações e outroselementos que poderão ser inseridos como critério de avaliação. Cada apresentação será avaliada pela tutora e pelosbolsistas, perfazendo uma média ponderada ao final da atividade.";
        }
    }
}
